last.fm code improvements
josephbeattie/Fluent-Media-Player-Dev pull request #175
Opened 2022-06-18 19:19 UTC by YourOrdinaryCat

**Resolved / Related Issues**
This PR improves the code for last.fm handling.

**Details of Changes**
- Added a new LastFMViewModel
- Added helper method to get encoded hashes from strings
- Cleaned up methods, switched to the WinRT Cryptography and Http classes

**Validation**
The changes are not yet functional, due to one of the API calls returning 400. Specifically, last.fm gives error 13:

`<error code="13">Invalid method signature supplied</error>`

This happens as soon as HttpClient attempts to get a string from `endUri` in the `TryAuthenticateAsync` method.

**Screenshots / Videos (optional)**
None.

2022-06-19 11:23 UTC, itsWindows11 approved these changes

2022-06-19 12:12 UTC, itsWindows11 requested changes
When last.fm reports that it can't connect to the app, it seems to crash with a FileNotFoundException in TryAuthenticateAsync

2022-06-19 13:24 UTC, YourOrdinaryCat commented
How do you recreate that? Wrong credentials or something?

2022-06-19 19:23 UTC, itsWindows11 commented
> How do you recreate that? Wrong credentials or something?

It might happen in some cases after logging in then closing iirc but I wasn't able to reproduce the last.fm app connection issue again.

2022-06-21 00:14 UTC, YourOrdinaryCat commented
Seems to be a host unavailable/no internet access thing. Should be fixed now.

2022-06-21 09:13 UTC, itsWindows11 commented on Rise Media Player Dev/Settings/OnlineServicesPage.xaml.cs
> +            bool result = await ViewModel.TryAuthenticateAsync();
Can you add a try/catch here?

2022-06-21 09:16 UTC, itsWindows11 requested changes
Everything looks good, but try to add the suggestion.

2022-06-21 21:01 UTC, YourOrdinaryCat commented on Rise Media Player Dev/Settings/OnlineServicesPage.xaml.cs
> +            bool result = await ViewModel.TryAuthenticateAsync();
Added one for everything after the result, should be good with that.

2022-06-22 10:29 UTC, itsWindows11 approved these changes

2022-06-23 09:52 UTC, merged