Code improvements for media pages
josephbeattie/Fluent-Media-Player-Dev pull request #176
Opened 2022-07-08 18:22 UTC by YourOrdinaryCat

**Resolved / Related Issues**
Related closely to #160 

**Details of Changes**
This pull request aims to make the app follow the MVVM pattern more closely, which involves:
- Decoupling: the current way we handle collections is from MainViewModel, which has every single collection. This means we have a lot of boilerplate just to reset filtering and sorting, and it makes saving session state more difficult
- Less repetition: there's a lot of repeated code when it comes to handling playback and other actions within a given page. This makes the code behind of every page far larger than necessary, which can lead to inconsistencies when triggering different actions

**Validation**
Not yet finished.

**Screenshots / Videos (optional)**
Not necessary, at least for now.

2022-07-18 21:57 UTC, YourOrdinaryCat commented
AlbumsPage has DataTemplate related bugs as of now - mostly hangs and memory leaks when switching, and the template not applying sometimes. Switching to a custom control there is likely necessary, will add that within the next few commits.

2022-08-04 10:11 UTC, itsWindows11 requested changes
Looks good to me, but there are some changes that need to be addressed before merging.

2022-08-04 10:11 UTC, itsWindows11 commented on Rise Media Player Dev/Helpers/AddToPlaylistHelper.cs
> +        public void WatchFlyout(MenuFlyout flyout)
The correct name for this would be "AddPlaylistsToFlyout", since it doesn't really "watch" the flyout for playlist changes

2022-08-04 10:11 UTC, itsWindows11 commented on Rise Media Player Dev/UserControls/MediaPageBase.cs
> +                MediaViewModel = new(defaultProperty, dataSource,
You can use the `??=` operator here for simplicity when initializing `MediaViewModel`.

2022-08-04 10:11 UTC, itsWindows11 commented on Rise Media Player Dev/UserControls/MediaPageBase.cs
> +                throw new NotImplementedException("No other item type is supported at the moment.");
This might crash if an edit button exists for the artists page.

2022-08-04 10:15 UTC, itsWindows11 commented
Also, use the `ContextRequested` event for the context menu for the lists instead of `RightTapped` which only handles right click.

2022-08-04 13:36 UTC, YourOrdinaryCat commented on Rise Media Player Dev/UserControls/MediaPageBase.cs
> +                throw new NotImplementedException("No other item type is supported at the moment.");
What should the command open up? The edit button on ArtistSongsPage currently opens up LibraryPageEditDialog, but that seems to be for customization of the page itself and not the artist.

2022-08-04 13:38 UTC, itsWindows11 commented on Rise Media Player Dev/UserControls/MediaPageBase.cs
> +                throw new NotImplementedException("No other item type is supported at the moment.");
Idk, leave it unimplemented for now, you can disregard this and remove the edit command for now. I'll try to see if there's a solution.

2022-08-04 14:17 UTC, YourOrdinaryCat commented
Should be good now.

2022-08-04 14:27 UTC, itsWindows11 approved these changes
LGTM

2022-08-04 14:28 UTC, merged