Initial equalizer implementation
josephbeattie/Fluent-Media-Player-Dev pull request #181
Opened 2022-08-08 19:46 UTC by itsWindows11

2022-08-12 03:44 UTC, YourOrdinaryCat requested changes
There's some changes I think we should make, specially with settings handling.

2022-08-12 03:44 UTC, yourordinarycat commented on Rise Media Player Dev/Settings/ViewModels/SettingsViewModel.cs
> +                float[] gainArray = { Convert.ToSingle(Gain["0"]), Convert.ToSingle(Gain["1"]), Convert.ToSingle(Gain["2"]), Convert.ToSingle(Gain["3"]), Convert.ToSingle(Gain["4"]), Convert.ToSingle
I think we could simplify things in the settings. A lot of the complexity seems to be there because of how we have to handle 1. the player not being there yet, and 2. enabling/disabling effects. I have some things in mind that could make it better, specially for 1.

2022-08-12 03:44 UTC, yourordinarycat commented on Rise.Effects/EqualizerEffect.cs
> +                var supportedEncodingProperties = new List<AudioEncodingProperties>();
The value of `SupportedEncodingProperties` doesn't seem to change ever, a backing field and a null check would be nicer here.

2022-08-12 03:44 UTC, yourordinarycat commented on Rise Media Player Dev/Settings/ViewModels/SettingsViewModel.cs
> +                ApplicationDataCompositeValue default1 = new();
I think we could avoid creating the default value every time here, maybe make this static? This value is fetched pretty frequently, so not recreating it every time would be better.

2022-08-12 03:44 UTC, yourordinarycat commented on Rise Media Player Dev/Dialogs/EqualizerDialog.xaml.cs
> +            list = new List<EqualizerSliderViewModel>()
A loop here would be more appropriate. For the record, composite values are dictionaries under the hood, and those implement key-value pair iterables, so you can iterate over them using `foreach`.

2022-08-12 09:49 UTC, itsWindows11 commented on Rise Media Player Dev/Settings/ViewModels/SettingsViewModel.cs
> +                float[] gainArray = { Convert.ToSingle(Gain["0"]), Convert.ToSingle(Gain["1"]), Convert.ToSingle(Gain["2"]), Convert.ToSingle(Gain["3"]), Convert.ToSingle(Gain["4"]), Convert.ToSingle
Seems like you implemented this change, will resolve this along with the others.

2022-08-12 09:49 UTC, itsWindows11 commented on Rise.Effects/EqualizerEffect.cs
> +                var supportedEncodingProperties = new List<AudioEncodingProperties>();
Done.

2022-08-12 09:50 UTC, itsWindows11 commented on Rise Media Player Dev/Settings/ViewModels/SettingsViewModel.cs
> +                ApplicationDataCompositeValue default1 = new();
Done.

2022-08-20 02:41 UTC, YourOrdinaryCat reviewed
Looks good to me so far, although I did find one bug - when updating the EQ settings, the new profile won't apply until you switch to a different song. We could have a float array property that, when updated, reapplies all the needed filters.

2022-08-20 04:13 UTC, YourOrdinaryCat approved these changes

2022-08-24 00:51 UTC, merged