Setup experience improvements
josephbeattie/Fluent-Media-Player-Dev pull request #193
Opened 2022-09-28 14:13 UTC by YourOrdinaryCat

**Resolved / Related Issues**
None.

**Details of Changes**
These changes improve the code used during setup, fixing a memory leak, adding lottie animations, improving performance, improving the way localized strings are handled, and removing unused code.

**Validation**
- [x] Built and ran the app
- [x] Compared to the previous setup
- [x] Went through the setup

**Screenshots / Videos (optional)**
https://imgur.com/a/7tBN9Gq

2022-09-29 16:28 UTC, itsWindows11 commented
Is this still WIP?

2022-09-30 19:20 UTC, YourOrdinaryCat commented
There's a few improvements I want to make before requesting a review, mostly to the navigation related code.

2022-10-01 18:38 UTC, itsWindows11 requested changes
Good changes, but I think you should make it look more like the old dialog i.e. leave more space for the icon and make it larger.

Other changes to the code are suggested below.

2022-10-01 18:38 UTC, itsWindows11 commented on Rise Media Player Dev/Dialogs/SetupDialogContent.xaml.cs
> +            Navigate(SlideNavigationTransitionEffect.FromBottom);
Keep the FromRight transition maybe?

2022-10-01 18:38 UTC, itsWindows11 commented on Rise Media Player Dev/Dialogs/SetupDialogContent.xaml.cs
> +            switch (ViewModel.SetupProgress)
We can use an if statement for this instead.

2022-10-03 02:49 UTC, YourOrdinaryCat commented
> Good changes, but I think you should make it look more like the old dialog i.e. leave more space for the animated icon and make it larger.

The visual player is technically the same size (128x128), but the animation itself seems to be a bit smaller. It looks close with a -16 margin though:

![image](https://user-images.githubusercontent.com/49221554/193493010-124fff1f-00a8-4283-b9f4-95a19f850286.png)

2022-10-03 09:24 UTC, itsWindows11 commented
I mean make the right side smaller like the old setup dialog.

2022-10-03 09:37 UTC, itsWindows11 commented
Like in here for example:
![image](https://user-images.githubusercontent.com/81253203/193546371-2f728bac-6ef1-44dc-9235-e8d8e7c83840.png)

2022-10-05 13:50 UTC, YourOrdinaryCat commented
Should be good now:

![image](https://user-images.githubusercontent.com/49221554/194076880-d0396220-0cbd-409a-8975-a3ee29c91d86.png)

2022-10-05 15:56 UTC, itsWindows11 approved these changes
LGTM

2022-10-05 16:17 UTC, merged