CQ: Improve notification JSON backend code, add notification when app crashes
josephbeattie/Fluent-Media-Player-Dev pull request #207
Opened 2022-11-21 15:10 UTC by itsWindows11

**Resolved / Related Issues**
As far as I know there are no issues related to this.

**Details of Changes**
Add details of changes here.
- Switched to notification models for JSON data storage.
- Fixed an issue where no new message will show up when the app is crashing.

**Validation**
How did you test these changes?
- [x] Built and ran the app

**Screenshots / Videos (optional)**
No screenshots.

2022-11-22 00:14 UTC, YourOrdinaryCat requested changes
Overall improvement, though there's still a few things that could be better. Could we open a different PR after this one for general improvements to the backend controllers? Of course, if we open another one this would only need to address the second comment.

2022-11-22 00:14 UTC, YourOrdinaryCat commented on Rise Media Player Dev/ViewModels/MainViewModel.cs
>              var notifications = await App.NBackendController.GetAsync();
Do we ever display saved notifications outside of that dialog? Loading it at this point would only slow down startup if we don't. Maybe load it only when first opening the dialog?

Thinking about this now, we already have to create an instance of the backend controller, so we could maybe move the list itself to it? Like what we already do for NavigationView items, it would also play better with lazy initialization, though I guess that's unrelated.

2022-11-22 00:14 UTC, YourOrdinaryCat commented on Rise Media Player Dev/ViewModels/PlaylistViewModel.cs
>                      OnPropertyChanged(nameof(Videos));
We could replace this code with an auto property, better change it to:

```C#
public SafeObservableCollection<VideoViewModel> Videos { get; } = new();
```

The collection is already observable either way, shouldn't be an issue

2022-11-25 13:14 UTC, itsWindows11 commented on Rise Media Player Dev/ViewModels/PlaylistViewModel.cs
>                      OnPropertyChanged(nameof(Videos));
Should be resolved by latest commit.

2022-11-25 13:18 UTC, itsWindows11 commented on Rise Media Player Dev/ViewModels/MainViewModel.cs
>              var notifications = await App.NBackendController.GetAsync();
Makes sense, we might have to do that for playlists too but yeah it's out of scope.

2022-11-25 17:06 UTC, YourOrdinaryCat approved these changes

2022-11-25 17:06 UTC, merged