Improved playlist importing, added WPL/ZPL support
josephbeattie/Fluent-Media-Player-Dev pull request #214
Opened 2022-12-23 20:59 UTC by itsWindows11

**Resolved / Related Issues**
No related GitHub issue.

**Details of Changes**
Add details of changes here.
- Added WPL/ZPL playlist parsing support.

**Validation**
How did you test these changes?
- [x] Built and ran the app

**Screenshots / Videos (optional)**
No screenshots.

2023-01-17 23:36 UTC, YourOrdinaryCat requested changes
Pretty good so far, merging the resource cleanup PR first would avoid conflicts with translations so I'd suggest waiting for that.

2023-01-17 23:36 UTC, YourOrdinaryCat commented on Rise Media Player Dev/Views/Playlists/PlaylistsPage.xaml
> +                        <MenuFlyoutItem Tag="FromFile" Text="From file" Click="ImportPlaylist_Click">
Using resources here would be nice, though I guess we should merge the resource cleanup PR first to avoid conflicts.

2023-01-17 23:36 UTC, YourOrdinaryCat commented on Rise Media Player Dev/Views/Playlists/PlaylistsPage.xaml.cs
> +            switch ((sender as FrameworkElement).Tag)
Could we use 2 event handlers here? So instead of `ImportPlaylist_Click`, we could have `ImportFromFile_Click` and `ImportFromFolder_Click`.

2023-01-18 06:00 UTC, yoshiask commented on Rise Media Player Dev/Views/Playlists/PlaylistsPage.xaml.cs
> +            switch ((sender as FrameworkElement).Tag)
> `(sender as FrameworkElement).Tag`
This code is kind of odd. Using `as` is only useful if you can handle the null value. In this case, since you're immediately getting `Tag`, it'll throw anyway if `sender` wasn't a `FrameworkElement`. This means that you'll get a `NullReferenceException`, which isn't as helpful as the following would give:
```cs
((FrameworkElement)sender).Tag
```
This would throw an `InvalidCastException`-- a much more useful error message.

2023-01-18 09:50 UTC, itsWindows11 commented on Rise Media Player Dev/Views/Playlists/PlaylistsPage.xaml
> +                        <MenuFlyoutItem Tag="FromFile" Text="From file" Click="ImportPlaylist_Click">
We can merge this first and fix that later in the resource cleanup PR, too. I think merging this first would be a good idea.

2023-01-18 09:53 UTC, itsWindows11 commented on Rise Media Player Dev/Views/Playlists/PlaylistsPage.xaml.cs
> +            switch ((sender as FrameworkElement).Tag)
That makes sense. I think that might require a separate refactoring PR because we use
```
(sender as FrameworkElement).Tag
```
... almost everywhere IIRC.

2023-01-18 10:00 UTC, itsWindows11 commented on Rise Media Player Dev/Views/Playlists/PlaylistsPage.xaml.cs
> +            switch ((sender as FrameworkElement).Tag)
Should be fixed in 79a5ce41619c9a501609d64b76d960d1dda12314 for now.

2023-01-19 17:33 UTC, YourOrdinaryCat approved these changes

2023-01-19 17:34 UTC, merged