Grouping in media lists
josephbeattie/Fluent-Media-Player-Dev pull request #222
Opened 2023-03-10 15:29 UTC by YourOrdinaryCat

**Resolved / Related Issues**
- Closes #128
- Closes #216

**Details of Changes**
This PR replaces the `AdvancedCollectionView` used for sorting with a new type that allows for both grouping and sorting - `GroupedCollectionView`. It allows grouping the lists found across the app, and thanks to changes to the way sort descriptions are handled, improves performance.

**Validation**
How did you test these changes?
- [x] Built and ran the app

**Screenshots / Videos (optional)**
![SemanticZoom in albums, zoomed out](https://user-images.githubusercontent.com/49221554/224351030-395a9417-5d5b-4795-a113-1f65b16b0491.png)

![SemanticZoom in songs, zoomed out](https://user-images.githubusercontent.com/49221554/224351207-0089b6d7-67dc-48e1-9e66-342a6d2d9523.png)

![Grouped songs ListView](https://user-images.githubusercontent.com/49221554/224355166-86253be4-5e25-42b5-a900-cc7ccd58edb3.png)

2023-03-10 19:28 UTC, esibruti commented
I don't know if it's planned but will these options work correctly with this MR?

![image](https://user-images.githubusercontent.com/78214358/224408060-5465487f-b1a9-4356-a574-48570c901cb8.png)

2023-03-10 19:35 UTC, YourOrdinaryCat commented
All of them should work correctly already :) just needs a few fixes to make it more usable.

2023-03-10 19:37 UTC, esibruti commented
Are these options even saved so they don't disappear again?
Btw, great job this MR is.

2023-03-10 19:48 UTC, YourOrdinaryCat commented
They should be getting saved for pages that allow for custom sorting (so Songs, Albums, and Videos). Haven't fully checked Videos though, seems like there's a race condition we have to fix because it crashes.

2023-03-10 20:15 UTC, YourOrdinaryCat commented
> Are these options even saved so they don't disappear again?

Yes indeed, just fixed the crash so it should be working for songs, albums, and videos :)

2023-03-12 22:09 UTC, itsWindows11 commented on Rise Media Player Dev/ResourceDictionaries/CardStyles.xaml
> +    </Style>
These changes seem to break the about card border appearance in the artist songs page.

2023-03-12 22:11 UTC, itsWindows11 commented on Rise Media Player Dev/ResourceDictionaries/ListStyles.xaml
> +        <Setter Property="HorizontalContentAlignment" Value="Stretch" />
We can base on `StretchedListViewItemStyle` instead of basing on the default style and then setting the HorizontalContentAlignment property, that's what the style is for.

2023-03-12 22:12 UTC, itsWindows11 commented on Rise Media Player Dev/ResourceDictionaries/ListStyles.xaml
> +                        CornerRadius="{ThemeResource SongListViewItemCornerRadius}"
I don't think we have to change the corner radius when the theme gets changed.
```suggestion
                        CornerRadius="{StaticResource SongListViewItemCornerRadius}"
```

2023-03-12 22:17 UTC, itsWindows11 commented on Rise Media Player Dev/Views/Albums/AlbumsPage.xaml
> +        <DataTemplate x:Key="GroupOverviewLetterItemTemplate" x:DataType="ICollectionViewGroup">
Try to put these in separate resource files if you can.

2023-03-12 22:21 UTC, itsWindows11 requested changes
Haven't tested the PR yet but it looks mostly good to me. There are a few changes that should be done.

2023-03-13 10:15 UTC, itsWindows11 requested changes
Seems like a regression found in the last two commits, but opening the songs page initially results in this until I choose a sort option.

![image](https://user-images.githubusercontent.com/81253203/224672615-1aef2ce9-93ff-4c7a-a0fd-5b3ed5e6005e.png)

2023-03-15 21:55 UTC, YourOrdinaryCat commented on Rise Media Player Dev/ResourceDictionaries/CardStyles.xaml
> +    </Style>
Actually just forgot to set the row number, should be working now.

2023-03-15 23:03 UTC, YourOrdinaryCat commented on Rise Media Player Dev/Views/Albums/AlbumsPage.xaml
> +        <DataTemplate x:Key="GroupOverviewLetterItemTemplate" x:DataType="ICollectionViewGroup">
How would we handle the converter in that case?

2023-03-16 12:25 UTC, itsWindows11 commented on Rise Media Player Dev/Views/Albums/AlbumsPage.xaml
> +        <DataTemplate x:Key="GroupOverviewLetterItemTemplate" x:DataType="ICollectionViewGroup">
I guess put it alongside the other resources if that's what you meant.

2023-04-09 10:27 UTC, itsWindows11 approved these changes
LGTM, just fixed a crash when sorting.

2023-04-09 10:28 UTC, merged