Improvements to navigation
josephbeattie/Fluent-Media-Player-Dev pull request #234
Opened 2023-04-19 19:24 UTC by YourOrdinaryCat

**Resolved / Related Issues**
I don't know if there's any on GitHub, but it is a known problem we've been trying to fix for a while.

**Details of Changes**
We used to save the state of NavigationView items during app suspension. However, this approach was somewhat problematic:
- The suspending event has a deadline - a pretty short one at that
- During suspension, we get low priority access to resources, which means we can't always save state fast enough
- If the app crashes, everything's up in the air, we can't expect suspension to just work

Navigation state is now saved when any modification that requires serializing again takes place. There's also a lot of improvements to the overall structure of the code, and we can add or remove items across app updates. Performance wise, deserialization should be way faster - on my end I noticed up to a 1s improvement in some cases.

All playlists are now pinned to the NavigationView as well.

**Validation**
How did you test these changes?
- [x] Built and ran the app in debug and release mode - we had some problems with .NET Native in the past after all

**Screenshots / Videos (optional)**
None - the UI didn't really change, aside from playlist pinning options being removed

2023-04-20 09:55 UTC, itsWindows11 approved these changes
LGTM. Can you add source generation for System.Text.Json? Might improve performance a bit more, but it's fast already.

2023-04-20 10:00 UTC, itsWindows11 commented on Rise Media Player Dev/Settings/NavigationPage.xaml
> +                            <FontIcon Glyph="{x:Bind DefaultIcon}" />
You should use the [WCT's FontIconExtension](https://learn.microsoft.com/en-us/windows/communitytoolkit/extensions/iconmarkupextensions#fonticonextension) instead, as other settings controls use it.

2023-04-20 10:00 UTC, itsWindows11 commented on Rise Media Player Dev/Settings/NavigationPage.xaml
> +                            <FontIcon Glyph="&#xE8D2;" />
Same as above

2023-04-20 10:02 UTC, itsWindows11 commented on Rise.Data/Navigation/Items/NavigationItemDestination.cs
> +        public string AccessKey { get; init; }
Do access keys ever work?

2023-04-20 10:06 UTC, itsWindows11 requested changes
Looks mostly good to me, just did a funny for some reason but anyways there are a few changes that should be done.

Also, can you add source generation for navigation in System.Text.Json? Might improve performance a bit more, but it's fast already.

2023-04-20 17:01 UTC, yourordinarycat commented on Rise Media Player Dev/Settings/NavigationPage.xaml
> +                            <FontIcon Glyph="{x:Bind DefaultIcon}" />
Markup extensions can't be used with Binding or x:Bind, fixed it for headers though.

2023-04-20 17:03 UTC, YourOrdinaryCat commented on Rise.Data/Navigation/Items/NavigationItemDestination.cs
> +        public string AccessKey { get; init; }
They work on my end - they're invoked with Alt + Key

2023-04-20 17:03 UTC, itsWindows11 commented on Rise Media Player Dev/Settings/NavigationPage.xaml
> +                            <FontIcon Glyph="{x:Bind DefaultIcon}" />
Oh right, apparently I was looking at the wrong line.

2023-04-21 03:31 UTC, itsWindows11 approved these changes

2023-04-21 03:31 UTC, merged