readme.md updates: squashed typos, improved explanations and a mature experience
josephbeattie/Fluent-Media-Player-Dev pull request #66
Opened 2021-12-03 09:57 UTC by dlphin11

in this commit, i had:
1. fixed the dialect inconsistencies between American and British English;
2. improved some explanations for a better general understanding at a glance;
3. improved punctuation and capitalisation;
4. added a more serious nature to the document.

i think these updates will generally improve the main page for new visitors to come.

2021-12-03 09:58 UTC, dlphin11 commented on readme.md
> -[Contribute to this Project](https://github.com/Rise-Software/Rise-Media-Player)
improved capitalisation

2021-12-03 09:58 UTC, dlphin11 commented on readme.md
> -**Rise Media Player** brings all of your media to a whole new level. If it's videos, the music stored on your devices, discs or even your favourite streaming services; you'll love our player. One lib
removed repetition and added some spice to it

2021-12-03 09:59 UTC, dlphin11 commented on readme.md
> +### **Pre-Alpha 3 is out now and includes video support! Download the installer from the download link below or clone the repository to build.**
improved order of ideas

2021-12-03 10:00 UTC, dlphin11 commented on readme.md
little QOL improvements

2021-12-03 10:00 UTC, itsWindows11 commented on readme.md
> +* In next step select Local machine (An UAC prompt may appear. Click Yes to continue);
```suggestion
* In next step select Local machine (A UAC prompt may appear. Click Yes to continue);
```

2021-12-03 10:01 UTC, dlphin11 commented on readme.md
> +**Disclaimer**: The actual product may not include all the functions featured in this mock-up. Some of them are being tested internally or planned to release later.
what was that? it said that the mockup doesn't have all the features from the app??

2021-12-03 10:01 UTC, dlphin11 commented on readme.md
> +* Pick up where you left off
improved capitalisation

2021-12-03 10:01 UTC, dlphin11 commented on readme.md
fixed american-british inconsistency

2021-12-03 10:01 UTC, dlphin11 commented on readme.md
> +* [**Rareș (@dlphin11)**](https://github.com/dlphin11)
corrected this ahah

2021-12-03 10:01 UTC, dlphin11 commented on readme.md
> +* Confirmation windows will appear. Now, try installing the .msixbundle!
better capitalisation

2021-12-03 10:02 UTC, itsWindows11 requested changes
Looks good so far, but there's one slight typo here

2021-12-03 10:03 UTC, itsWindows11 commented on readme.md
> +* In next step select Local machine (An UAC prompt may appear. Click Yes to continue);
```suggestion
* In next step select Local machine (A UAC prompt may appear. Click Yes to continue);
```

2021-12-03 10:04 UTC, dlphin11 commented
> Looks good so far, but there's one slight typo here

isn't it mandatory for the article to be 'an' when you have a vocale succeeding it?

2021-12-03 10:09 UTC, itsWindows11 commented
> > Looks good so far, but there's one slight typo here
> 
> isn't it mandatory for the article to be 'an' when you have a vocale succeeding it?

I don't think using 'an' applies to abbreviations.

2021-12-09 14:00 UTC, itsWindows11 commented
@dlphin11 Any updates?

2022-03-09 07:54 UTC, closed without merging